### ISSUE TITLE
function offset from GameAssembly.dll + Offset ?

### ISSUE THREAD

**Issue by ansav12** [lanylow/honkai-dumper#1]
`impl Il2CppFunctions {
  pub fn new(base: usize) -> Self {
    Il2CppFunctions {
      il2cpp_domain_get: get_method_ptr(base + 0x1cf2e48),
      il2cpp_domain_get_assemblies: get_method_ptr(base + 0x1cf2e58),
      il2cpp_assembly_get_image: get_method_ptr(base + 0x1cf2d10),
      il2cpp_image_get_class_count: get_method_ptr(base + 0x1cf3178),
      il2cpp_image_get_class: get_method_ptr(base + 0x1cf3180),
      il2cpp_class_get_methods: get_method_ptr(base + 0x1cf2d78),
      il2cpp_class_get_name: get_method_ptr(base + 0x1cf2d88),
      il2cpp_class_get_namespace: get_method_ptr(base + 0x1cf2d98),
      il2cpp_method_get_name: get_method_ptr(base + 0x1cf2fd8)
    }
  }
}`

**Comment by lanylow** [comment]
No, these offsets are relative to UnityPlayer.dll. The Il2CppFunctions object is created [here](https://github.com/lanylow/honkai-dumper/blob/main/src/unity/api.rs#L37).
