### ISSUE TITLE
I want 2.4(2.351) dump

### ISSUE THREAD

**Issue by yhyzzm** [lanylow/honkai-dumper#2]
I really need dump for 2.3.51 and would appreciate it if you could provide it
[download2.3.51](https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip)

**Comment by lanylow** [comment]
If you need to dump a specific version of the game you'll need to update offsets of functions defined [here](https://github.com/lanylow/honkai-dumper/blob/main/src/unity/functions.rs#L19).

**Comment by yhyzzm** [comment]
> If you need to dump a specific version of the game you'll need to change the offsets of functions defined [here](https://github.com/lanylow/honkai-dumper/blob/main/src/unity/functions.rs#L19).如果需要转储特定版本的游戏，则需要更改此处定义的函数的偏移量。

ok

**Comment by yhyzzm** [comment]
> If you need to dump a specific version of the game you'll need to change the offsets of functions defined [here](https://github.com/lanylow/honkai-dumper/blob/main/src/unity/functions.rs#L19).如果需要转储特定版本的游戏，则需要更改此处定义的函数的偏移量。

OK，but how i can got the function offset？

**Comment by lanylow** [comment]
The only option you have is to reverse engineer UnityPlayer.dll using tools like IDA.

**Comment by yhyzzm** [comment]
> The only option you have is to reverse engineer UnityPlayer.dll using tools like IDA.

Thank you, I will try this method
