### ISSUE TITLE
Maybe these are offsets for the new version

### ISSUE THREAD

**Issue by kongbaiz** [lanylow/honkai-dumper#4]
il2cpp_domain_get: get_method_ptr(base + 0x1D59DD0),
      il2cpp_domain_get_assemblies: get_method_ptr(base + 0x1D59DE0),
      il2cpp_assembly_get_image: get_method_ptr(base + 0x1D59C88),
      il2cpp_image_get_class_count: get_method_ptr(base + 0x1D5A100),
      il2cpp_image_get_class: get_method_ptr(base + 0x1D5A108),
      il2cpp_class_get_methods: get_method_ptr(base + 0x1D59CF0),
      il2cpp_class_get_name: get_method_ptr(base + 0x1D59D00),
      il2cpp_class_get_namespace: get_method_ptr(base + 0x1D59D10),
      il2cpp_method_get_name: get_method_ptr(base + 0x1D59F60)

**Comment by lanylow** [comment]
These are correct, thanks.
